### ISSUE TITLE
Fire spread goes underground - unable to extinguish these flames.

### ISSUE THREAD

**Issue by Duderocktv** [gimicze/firescript#4]
As the title says, sometimes the fire spread goes underground and the water is unable to reach the base through collision

**Comment by gimicze** [comment]
I changed an argument in the native which helps calculate the ground elevation in a20898f. If that doesn't help, I won't be able to fix this unfortunately - there are more-layer ground collisions on some places. It would definitely help decreasing the spread of the fire and creating more "flames" rather than a one large one.

**Comment by Duderocktv** [comment]
Unfortunately this doesn't seem to work. It seems the biggest difficulty is getting these fires under control.
Are you able to fully extinguish a spawned fire? We have a firetruck and a few fire extinguishers going and nothing keeps these fires at bay

**Comment by gimicze** [comment]
Everything works just fine for me and many other servers. Maybe try switching your FXServer's artifact (which one are you using?). Also check the console for any errors, as this behavior is weird and unprecedented (or at least hasn't been reported yet). Focus on the log around when the script gets started.

**Comment by Duderocktv** [comment]
Fixed! The issue was starting the script live!
When the server restarts with the script enabled the flames are tameable!

**Comment by gimicze** [comment]
Glad you got it sorted out! If there are ever any other problems, feel free to open another issue.
