### ISSUE TITLE
Fires can't be put out anymore

### ISSUE THREAD

**Issue by IronEh** [gimicze/firescript#7]
I currently have 13 fires setup and working on my server. However fires that could be put out previously, not longer can be. By simply watching the fire it seems like it's spreading faster then it's being put out. Even with the water cannon from a fire truck. 

At first I assumed it was down to a setting when the fire was being created, but the problem has popped up with fires that were tested multiple times and worked previously as random spawns. 

At this point we have chosen to simply remake said fires and hope the problem doesn't pop up again. 

Could you provide insight on why this would be happening? No errors are showing in the log.

**Comment by gimicze** [comment]
Hi!

After a brief revision of the code I haven't found anything that could cause this. I suppose you're using v1.7.4, right?

Would you happen to have the old fires.json file?

Also, was it possible to put out single flames (one particle source) one by one, or did the water have no effect at all?

Thanks.

**Comment by IronEh** [comment]
I am yes. Here is the fires.json file. Fires 1-3 have been redone and work as of right now. I can't say the same for the rest. 

[fires.zip](https://github.com/gimicze/firescript/files/6506913/fires.zip)

Flames did appear to be going out, but would reignite almost immediately.

**Comment by gimicze** [comment]
I've had a look at the setup and have to say that this problem might just be caused by the number of particles being created in addition to a relatively highly set spread chance.

It seems like what looks like reignition of the fire is just that the particles disappeared for a moment. I understand that this only started to happen recently, but you'll probably have to change your graphics settings and reduce the number of flames as well as the spread chance (I'd suggest staying around 15-20).

Either way, let me know how it went.
